services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      IN_DOCKER: 1
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data


  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "55672:5672"
      - "15672:15672"

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A DTeamTest worker --loglevel=error
    depends_on:
      - rabbitmq
      - db

volumes:
  postgres_data:
