# Generated by Django 5.2.1 on 2025-05-16 15:03

import django.db.models.deletion
import main.constants
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=40)),
                ("lastname", models.CharField(max_length=40)),
                ("skills", models.TextField()),
                ("projects", models.TextField()),
                ("bio", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            (main.constants.ContactsTypeEnum["EMAIL"], "email"),
                            (main.constants.ContactsTypeEnum["PHONE"], "phone"),
                            (main.constants.ContactsTypeEnum["LINKEDIN"], "linkedin"),
                            (main.constants.ContactsTypeEnum["GITHUB"], "github"),
                            (main.constants.ContactsTypeEnum["WEBSITE"], "website"),
                        ],
                        max_length=50,
                    ),
                ),
                ("value", models.CharField(max_length=255)),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="main.cv",
                    ),
                ),
            ],
        ),
    ]
