# Generated by Django 5.2.1 on 2025-05-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_cv_skills_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
